import { StyleSheet } from "react-native";

export const colors = {
  bg: "#f8f7f0",
  ink: "#17211d",
  moss: "#426653",
  mint: "#dff4e9",
  mintBorder: "#b7dfc8",
  sand: "#ebe7dc",
  cardBorder: "#e5e0d6",
  inputBorder: "#d7d0c4",
  muted: "#6c6259",
  body: "#4f4943",
  white: "#fff",
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  flex: { flex: 1 },
  center: { alignItems: "center", justifyContent: "center", gap: 12 },
  header: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 12, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  brand: { fontSize: 22, fontWeight: "900", color: colors.ink },
  muted: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  body: { flex: 1, paddingHorizontal: 20 },
  bodyContent: { paddingBottom: 40 },
  authWrap: { padding: 20, paddingTop: 64 },
  hero: { fontSize: 42, lineHeight: 46, fontWeight: "900", color: colors.ink },
  heroSub: { marginTop: 12, marginBottom: 24, fontSize: 16, lineHeight: 24, color: colors.muted },
  title: { fontSize: 28, fontWeight: "900", color: colors.ink, marginTop: 20 },
  requiredNote: { color: colors.muted, fontSize: 13, marginTop: 8 },
  notice: { backgroundColor: colors.mint, borderColor: colors.mintBorder, borderWidth: 1, borderRadius: 8, padding: 14, marginTop: 16 },
  noticeTitle: { color: colors.ink, fontSize: 15, fontWeight: "900" },
  card: { backgroundColor: colors.white, borderColor: colors.cardBorder, borderWidth: 1, borderRadius: 8, padding: 16, marginTop: 12 },
  unreadCard: { borderColor: colors.moss, borderWidth: 2 },
  cardTitle: { color: colors.ink, fontSize: 17, fontWeight: "800", flexShrink: 1 },
  description: { color: colors.body, marginTop: 8, lineHeight: 20 },
  section: { marginTop: 22 },
  sectionTitle: { fontSize: 18, fontWeight: "900", color: colors.ink, marginBottom: 2 },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 },
  backButton: { alignSelf: "flex-start", marginTop: 18, borderRadius: 8, backgroundColor: colors.sand, paddingHorizontal: 12, paddingVertical: 8 },
  backText: { color: colors.moss, fontWeight: "900" },
  status: { backgroundColor: colors.mint, color: colors.moss, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999, overflow: "hidden" },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  chip: { backgroundColor: colors.mint, color: colors.moss, fontWeight: "700", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, overflow: "hidden", fontSize: 12 },
  primaryButton: { backgroundColor: colors.ink, borderRadius: 8, paddingVertical: 14, alignItems: "center", marginTop: 16 },
  primaryText: { color: colors.white, fontWeight: "900" },
  smallButton: { backgroundColor: colors.ink, borderRadius: 8, paddingVertical: 9, paddingHorizontal: 14 },
  smallButtonText: { color: colors.white, fontWeight: "800" },
  secondaryButton: { backgroundColor: colors.mint, borderRadius: 8, paddingVertical: 9, paddingHorizontal: 14, marginTop: 12, alignItems: "center" },
  secondaryText: { color: colors.moss, fontWeight: "900" },
  linkText: { color: colors.moss, fontWeight: "900", marginTop: 10 },
  ghostButton: { paddingVertical: 8, paddingHorizontal: 10, alignItems: "center" },
  ghostText: { color: colors.moss, fontWeight: "800" },
  segment: { flexDirection: "row", backgroundColor: colors.sand, borderRadius: 8, padding: 3, marginBottom: 12 },
  segmentButton: { flex: 1, alignItems: "center", paddingVertical: 10, borderRadius: 6 },
  segmentActive: { backgroundColor: colors.mint },
  segmentText: { fontWeight: "900", color: colors.ink },
  field: { marginTop: 12 },
  label: { color: colors.ink, fontWeight: "800", marginBottom: 6 },
  helperText: { color: colors.muted, fontSize: 12, marginBottom: 8 },
  input: { backgroundColor: colors.white, borderColor: colors.inputBorder, borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 12, color: colors.ink },
  inputWrap: { position: "relative" },
  inputWithButton: { paddingRight: 72 },
  visibilityButton: { position: "absolute", right: 8, top: 7, bottom: 7, justifyContent: "center", paddingHorizontal: 10, borderRadius: 6, backgroundColor: colors.mint },
  visibilityText: { color: colors.moss, fontWeight: "900", fontSize: 12 },
  textarea: { minHeight: 90, textAlignVertical: "top" },
  detailGrid: { marginTop: 16, gap: 10 },
  detailItem: { borderTopColor: colors.sand, borderTopWidth: 1, paddingTop: 10 },
  detailLabel: { color: colors.muted, fontSize: 12, fontWeight: "800", textTransform: "uppercase" },
  detailValue: { color: colors.ink, fontSize: 15, fontWeight: "800", marginTop: 3 },
  scoreRow: { flexDirection: "row", gap: 8 },
  scoreButton: { flex: 1, alignItems: "center", borderColor: colors.inputBorder, borderWidth: 1, borderRadius: 8, paddingVertical: 10, backgroundColor: colors.white },
  scoreButtonActive: { backgroundColor: colors.ink, borderColor: colors.ink },
  scoreText: { color: colors.moss, fontWeight: "900" },
  scoreTextActive: { color: colors.white },
  statusBox: { marginTop: 16, borderRadius: 8, backgroundColor: colors.bg, padding: 12 },
  commentBox: { marginTop: 12, borderTopColor: colors.sand, borderTopWidth: 1, paddingTop: 12 },
  statusTitle: { color: colors.ink, fontWeight: "900" },
  choice: { borderColor: colors.inputBorder, borderWidth: 1, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 9, backgroundColor: colors.white },
  choiceActive: { backgroundColor: colors.ink, borderColor: colors.ink },
  choiceText: { color: colors.moss, fontWeight: "800" },
  choiceTextActive: { color: colors.white },
  empty: { color: colors.muted, marginTop: 12 },
  tabBar: { borderTopColor: colors.sand, backgroundColor: colors.bg },
  errorText: { color: "#b23b3b", marginTop: 12, fontWeight: "700" },
});
